# Data Preprocessing UCI 303

## Refer ORIGNINAL last Copy is 16 May Before editing 

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('CleavelandHeartUCI.csv')

dataset.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

    ca  thal  target  
0  0.0   6.0       0  
1  3.0   3.0       1  
2  2.0   7.0       1  
3  0.0   3.0       0  
4  0.0   3.0       0

## Dataset Details

In [3]:
dataset.shape

(303, 14)

In [4]:
dataset.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [5]:
dataset.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.438944    0.679868    3.158416  131.689769  246.693069    0.148515   
std      9.038662    0.467299    0.960126   17.599748   51.776918    0.356198   
min     29.000000    0.000000    1.000000   94.000000  126.000000    0.000000   
25%     48.000000    0.000000    3.000000  120.000000  211.000000    0.000000   
50%     56.000000    1.000000    3.000000  130.000000  241.000000    0.000000   
75%     61.000000    1.000000    4.000000  140.000000  275.000000    0.000000   
max     77.000000    1.000000    4.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  299.000000   
mean     0.990099  149.607261    0.326733    1.039604    1.600660    0.672241   
std      0.994971   22.875003    0.469794    1.161075    0.616226    0.937438   
min      0.000000   71.000000    0.000000    0.000000    1.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    2.000000    0.000000   
75%      2.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    3.000000    3.000000   

             thal      target  
count  301.000000  303.000000  
mean     4.734219    0.458746  
std      1.939706    0.499120  
min      3.000000    0.000000  
25%      3.000000    0.000000  
50%      3.000000    0.000000  
75%      7.000000    1.000000  
max      7.000000    1.000000

In [6]:
dataset.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca          float64
thal        float64
target        int64
dtype: object

In [7]:
dataset.info

<bound method DataFrame.info of      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   1       145   233    1        2      150      0      2.3   
1     67    1   4       160   286    0        2      108      1      1.5   
2     67    1   4       120   229    0        2      129      1      2.6   
3     37    1   3       130   250    0        0      187      0      3.5   
4     41    0   2       130   204    0        2      172      0      1.4   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   45    1   1       110   264    0        0      132      0      1.2   
299   68    1   4       144   193    1        0      141      0      3.4   
300   57    1   4       130   131    0        0      115      1      1.2   
301   57    0   2       130   236    0        2      174      0      0.0   
302   38    1   3       138   175    0        0      173      0      0.0   

     slope   ca  thal  target  
0        3  0.0   6.0  

In [8]:
dataset.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          4
thal        2
target      0
dtype: int64

In [9]:
dataset.values.any()

True

## Remove Missing Data

In [10]:
dataset.dropna(inplace=True)

In [11]:
dataset.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [12]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [13]:
data = dataset.copy()

In [14]:
data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

    ca  thal  target  
0  0.0   6.0       0  
1  3.0   3.0       1  
2  2.0   7.0       1  
3  0.0   3.0       0  
4  0.0   3.0       0

In [15]:
data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [16]:
## For Chi Test
X1 = data.iloc[:,0:13] #independent columns
y1 = data.iloc[:,-1] #target column

##  Independent and Dependent Variables

In [17]:
X = dataset.iloc[:, :-1]
y = dataset.iloc[:, -1]

### Independent variables (also referred to as Features) are the input for a process that is being analyzes

In [18]:
X

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   1       145   233    1        2      150      0      2.3   
1     67    1   4       160   286    0        2      108      1      1.5   
2     67    1   4       120   229    0        2      129      1      2.6   
3     37    1   3       130   250    0        0      187      0      3.5   
4     41    0   2       130   204    0        2      172      0      1.4   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
297   57    0   4       140   241    0        0      123      1      0.2   
298   45    1   1       110   264    0        0      132      0      1.2   
299   68    1   4       144   193    1        0      141      0      3.4   
300   57    1   4       130   131    0        0      115      1      1.2   
301   57    0   2       130   236    0        2      174      0      0.0   

     slope   ca  thal  
0        3  0.0   6.0  
1        2  3.0   3.0  
2        2  2.0   7.0  
3        3  0.0   3.0  
4        1  0.0   3.0  
..     ...  ...   ...  
297      2  0.0   7.0  
298      2  0.0   7.0  
299      2  2.0   7.0  
300      2  1.0   7.0  
301      2  1.0   3.0  

[297 rows x 13 columns]

### Dependent variables are the output of the process.

In [19]:
y

0      0
1      1
2      1
3      0
4      0
      ..
297    1
298    1
299    1
300    1
301    1
Name: target, Length: 297, dtype: int64

### Objective 1 Achieved the objective to identify the significant features based on scores from both methods.

## Filter Based Feature Selections with Chi-Test

In [20]:
#apply SelectKBest class to extract top best features
bestfeatures = SelectKBest(score_func=chi2, k=10)
fit = bestfeatures.fit(X1,y1)
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(X.columns)
#concat two dataframes for better visualization
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Specs','Score'] #naming the dataframe columns
print(featureScores.nlargest(13,'Score')) #print best features

       Specs       Score
7    thalach  187.053104
11        ca   82.730613
9    oldpeak   68.570533
12      thal   65.221093
8      exang   35.508090
0        age   22.917697
4       chol   20.855084
3   trestbps   16.707463
2         cp   14.591587
6    restecg    8.134652
10     slope    7.828836
1        sex    7.444195
5        fbs    0.002547


In [21]:
featureScores

Specs       Score
0        age   22.917697
1        sex    7.444195
2         cp   14.591587
3   trestbps   16.707463
4       chol   20.855084
5        fbs    0.002547
6    restecg    8.134652
7    thalach  187.053104
8      exang   35.508090
9    oldpeak   68.570533
10     slope    7.828836
11        ca   82.730613
12      thal   65.221093

## Feature Importance ranking based on LR ;Remove chol and thalach  

In [22]:
import random
random.seed(101)
y = data['target'].copy()
x = data.drop(['target','chol','thalach'], axis=1).copy()
y

xpy=x
ypy=y

### 11 Atttributes chosen for the model evaluation

In [23]:
x

age  sex  cp  trestbps  fbs  restecg  exang  oldpeak  slope   ca  thal
0     63    1   1       145    1        2      0      2.3      3  0.0   6.0
1     67    1   4       160    0        2      1      1.5      2  3.0   3.0
2     67    1   4       120    0        2      1      2.6      2  2.0   7.0
3     37    1   3       130    0        0      0      3.5      3  0.0   3.0
4     41    0   2       130    0        2      0      1.4      1  0.0   3.0
..   ...  ...  ..       ...  ...      ...    ...      ...    ...  ...   ...
297   57    0   4       140    0        0      1      0.2      2  0.0   7.0
298   45    1   1       110    0        0      0      1.2      2  0.0   7.0
299   68    1   4       144    1        0      0      3.4      2  2.0   7.0
300   57    1   4       130    0        0      1      1.2      2  1.0   7.0
301   57    0   2       130    0        2      0      0.0      2  1.0   3.0

[297 rows x 11 columns]

In [24]:
x = np.array(x, dtype='float32')

In [25]:
y = np.array(y, dtype='float32')

In [26]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
std_scaler = StandardScaler()

In [27]:
import random
random.seed(101)
from sklearn.model_selection import train_test_split
(trainX, testX, trainY, testY) = train_test_split(x,y, test_size=0.2, random_state=101)

trainX=std_scaler.fit_transform(trainX)
testX=std_scaler.transform(testX)

In [28]:
trainX

array([[ 1.1752458 ,  0.66057825,  0.8494212 , ...,  0.66557413,
         0.329969  ,  1.1325955 ],
       [-1.3568748 ,  0.66057825, -2.2797935 , ..., -0.9440286 ,
         1.4012382 , -0.9243021 ],
       [ 1.3954302 , -1.5138252 , -0.19365042, ..., -0.9440286 ,
         0.329969  , -0.9243021 ],
       ...,
       [-0.14586055, -1.5138252 ,  0.8494212 , ..., -0.9440286 ,
        -0.74130017, -0.9243021 ],
       [-0.03576835, -1.5138252 , -0.19365042, ..., -0.9440286 ,
        -0.74130017, -0.9243021 ],
       [ 0.18441604, -1.5138252 , -1.236722  , ...,  0.66557413,
        -0.74130017, -0.9243021 ]], dtype=float32)

In [29]:
trainY

array([1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1.,
       0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1.,
       1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1.,
       0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1.,
       0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1.,
       1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1.,
       0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0.,
       1., 0., 0., 1., 0.

In [30]:
QC = pd.DataFrame(trainX)

In [31]:
QC

0         1         2         3         4         5         6  \
0    1.175246  0.660578  0.849421  0.190017 -0.402200  1.040962 -0.720577   
1   -1.356875  0.660578 -2.279794  0.901367 -0.402200  1.040962 -0.720577   
2    1.395430 -1.513825 -0.193650  1.120244 -0.402200 -0.972980 -0.720577   
3    0.844969 -1.513825  0.849421  1.010806 -0.402200 -0.972980  1.387777   
4   -1.907336 -1.513825 -0.193650 -0.630772 -0.402200 -0.972980 -0.720577   
..        ...       ...       ...       ...       ...       ...       ...   
232  1.175246 -1.513825  0.849421  1.010806 -0.402200  1.040962 -0.720577   
233  1.175246 -1.513825 -0.193650  1.557998 -0.402200  1.040962 -0.720577   
234 -0.145861 -1.513825  0.849421  0.354174 -0.402200  1.040962 -0.720577   
235 -0.035768 -1.513825 -0.193650  0.190017  2.486326 -0.972980 -0.720577   
236  0.184416 -1.513825 -1.236722  0.463613 -0.402200  1.040962 -0.720577   

            7         8         9        10  
0    1.516609  0.665574  0.329969  1.132596  
1   -0.216450 -0.944029  1.401238 -0.924302  
2   -0.909673 -0.944029  0.329969 -0.924302  
3    0.303468  0.665574 -0.741300 -0.924302  
4   -0.909673 -0.944029 -0.741300 -0.924302  
..        ...       ...       ...       ...  
232 -0.043144  0.665574  2.472507  1.132596  
233 -0.216450 -0.944029 -0.741300 -0.924302  
234 -0.909673 -0.944029 -0.741300 -0.924302  
235 -0.909673 -0.944029 -0.741300 -0.924302  
236  0.216815  0.665574 -0.741300 -0.924302  

[237 rows x 11 columns]

# LR Classifiers with Grid Search methodology

In [34]:
LRtrainX=trainX
LRtestX=testX
LRtrainY=trainY
LRtestY=testY

In [35]:
LRtrainX

array([[ 1.1752458 ,  0.66057825,  0.8494212 , ...,  0.66557413,
         0.329969  ,  1.1325955 ],
       [-1.3568748 ,  0.66057825, -2.2797935 , ..., -0.9440286 ,
         1.4012382 , -0.9243021 ],
       [ 1.3954302 , -1.5138252 , -0.19365042, ..., -0.9440286 ,
         0.329969  , -0.9243021 ],
       ...,
       [-0.14586055, -1.5138252 ,  0.8494212 , ..., -0.9440286 ,
        -0.74130017, -0.9243021 ],
       [-0.03576835, -1.5138252 , -0.19365042, ..., -0.9440286 ,
        -0.74130017, -0.9243021 ],
       [ 0.18441604, -1.5138252 , -1.236722  , ...,  0.66557413,
        -0.74130017, -0.9243021 ]], dtype=float32)

In [36]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [43]:
LRTrainX=std_scaler.fit_transform(LRtrainX)
LRtestX=std_scaler.transform(LRtestX)

In [46]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import GridSearchCV

In [47]:
LRparameters = {'penalty':['l1','l2'], 'C':[1.0, 10.0, 100.0, 1000.0]}

In [48]:
import random
random.seed(101)
LRmodel = LogisticRegression()
clf = GridSearchCV(LRmodel, LRparameters, verbose=2 ,cv=10)

In [49]:
clf.fit(LRtrainX, LRtrainY)

Fitting 10 folds for each of 8 candidates, totalling 80 fits
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l2; total time=   0.0s
[CV] END ..................................C=1.0

C:\Users\Adrian\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
40 fits failed out of a total of 80.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
40 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Adrian\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Adrian\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\Adrian\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 449, in _check_solver
    % (solver, penalty

GridSearchCV(cv=10, estimator=LogisticRegression(),
             param_grid={'C': [1.0, 10.0, 100.0, 1000.0],
                         'penalty': ['l1', 'l2']},
             verbose=2)

In [50]:
logreg_best_param = clf.best_params_
print("Best params for LR:", logreg_best_param)

Best params for LR: {'C': 10.0, 'penalty': 'l2'}


In [51]:
import random
random.seed(101)
LRpredict = clf.predict(LRtestX)
print(classification_report(LRtestY,LRpredict))
print(confusion_matrix(LRtestY, LRpredict))

              precision    recall  f1-score   support

         0.0       0.87      0.85      0.86        40
         1.0       0.71      0.75      0.73        20

    accuracy                           0.82        60
   macro avg       0.79      0.80      0.80        60
weighted avg       0.82      0.82      0.82        60

[[34  6]
 [ 5 15]]


In [52]:
logreg_accuracy_score = accuracy_score(LRtestY, LRpredict)
print("Best accuracy for LR11:", logreg_accuracy_score)

Best accuracy for LR: 0.8166666666666667


## Feature Importance ranking based on LR ;Remove thalach,chol,ca and sex

In [53]:
import random
random.seed(101)
y = data['target'].copy()
x = data.drop(['target','thalach','chol','ca','sex'], axis=1).copy()
y

xpy=x
ypy=y

In [54]:
x = np.array(x, dtype='float32')
y = np.array(y, dtype='float32')

In [55]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
std_scaler = StandardScaler()

In [56]:
import random
random.seed(101)
from sklearn.model_selection import train_test_split
(trainX, testX, trainY, testY) = train_test_split(x,y, test_size=0.2, random_state=101)

trainX=std_scaler.fit_transform(trainX)
testX=std_scaler.transform(testX)

In [57]:
QC = pd.DataFrame(trainX)

In [58]:
LRtrainX=trainX
LRtestX=testX
LRtrainY=trainY
LRtestY=testY

In [59]:
LRTrainX=std_scaler.fit_transform(LRtrainX)
LRtestX=std_scaler.transform(LRtestX)

In [60]:
LRparameters = {'penalty':['l1','l2'], 'C':[1.0, 10.0, 100.0, 1000.0]}

In [61]:
import random
random.seed(101)
LRmodel = LogisticRegression()
clf = GridSearchCV(LRmodel, LRparameters, verbose=2 ,cv=10)

In [62]:
clf.fit(LRtrainX, LRtrainY)

Fitting 10 folds for each of 8 candidates, totalling 80 fits
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l2; total time=   0.0s
[CV] END ..................................C=1.0

C:\Users\Adrian\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
40 fits failed out of a total of 80.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
40 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Adrian\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Adrian\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\Adrian\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 449, in _check_solver
    % (solver, penalty

GridSearchCV(cv=10, estimator=LogisticRegression(),
             param_grid={'C': [1.0, 10.0, 100.0, 1000.0],
                         'penalty': ['l1', 'l2']},
             verbose=2)

In [63]:
logreg_best_param9 = clf.best_params_
print("Best params for LR:", logreg_best_param9)

Best params for LR: {'C': 1.0, 'penalty': 'l2'}


In [64]:
import random
random.seed(101)
LRpredict = clf.predict(LRtestX)
print(classification_report(LRtestY,LRpredict))
print(confusion_matrix(LRtestY, LRpredict))

              precision    recall  f1-score   support

         0.0       0.86      0.75      0.80        40
         1.0       0.60      0.75      0.67        20

    accuracy                           0.75        60
   macro avg       0.73      0.75      0.73        60
weighted avg       0.77      0.75      0.76        60

[[30 10]
 [ 5 15]]


In [65]:
logreg_accuracy_score = accuracy_score(LRtestY, LRpredict)
print("Best accuracy for LR9:", logreg_accuracy_score)

Best accuracy for LR9: 0.75


## Feature Importance ranking based on LR ;Remove thalach , chol ,ca,sex,oldpeak,exang 

In [66]:
import random
random.seed(101)
y = data['target'].copy()
x = data.drop(['target','thalach','chol','ca','sex','oldpeak','exang'], axis=1).copy()
y

xpy=x
ypy=y

In [67]:
x = np.array(x, dtype='float32')
y = np.array(y, dtype='float32')

In [68]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
std_scaler = StandardScaler()

In [69]:
import random
random.seed(101)
from sklearn.model_selection import train_test_split
(trainX, testX, trainY, testY) = train_test_split(x,y, test_size=0.2, random_state=101)

trainX=std_scaler.fit_transform(trainX)
testX=std_scaler.transform(testX)

In [70]:
QC = pd.DataFrame(trainX)

In [71]:
LRtrainX=trainX
LRtestX=testX
LRtrainY=trainY
LRtestY=testY

In [72]:
LRTrainX=std_scaler.fit_transform(LRtrainX)
LRtestX=std_scaler.transform(LRtestX)

In [73]:
LRparameters = {'penalty':['l1','l2'], 'C':[1.0, 10.0, 100.0, 1000.0]}

In [74]:
import random
random.seed(101)
LRmodel = LogisticRegression()
clf = GridSearchCV(LRmodel, LRparameters, verbose=2 ,cv=10)

In [75]:
clf.fit(LRtrainX, LRtrainY)

Fitting 10 folds for each of 8 candidates, totalling 80 fits
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l1; total time=   0.0s
[CV] END ..................................C=1.0, penalty=l2; total time=   0.0s
[CV] END ..................................C=1.0

C:\Users\Adrian\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
40 fits failed out of a total of 80.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
40 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Adrian\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Adrian\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\Adrian\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 449, in _check_solver
    % (solver, penalty

GridSearchCV(cv=10, estimator=LogisticRegression(),
             param_grid={'C': [1.0, 10.0, 100.0, 1000.0],
                         'penalty': ['l1', 'l2']},
             verbose=2)

In [76]:
logreg_best_param9 = clf.best_params_
print("Best params for LR:", logreg_best_param9)

Best params for LR: {'C': 1.0, 'penalty': 'l2'}


In [77]:
import random
random.seed(101)
LRpredict = clf.predict(LRtestX)
print(classification_report(LRtestY,LRpredict))
print(confusion_matrix(LRtestY, LRpredict))

              precision    recall  f1-score   support

         0.0       0.84      0.68      0.75        40
         1.0       0.54      0.75      0.63        20

    accuracy                           0.70        60
   macro avg       0.69      0.71      0.69        60
weighted avg       0.74      0.70      0.71        60

[[27 13]
 [ 5 15]]


In [78]:
logreg_accuracy_score = accuracy_score(LRtestY, LRpredict)
print("Best accuracy for LR7:", logreg_accuracy_score)

Best accuracy for LR7: 0.7
